import { getServerSession } from "next-auth";
import { PrismaClient } from "@prisma/client";
import { CheckCircle2, Zap } from "lucide-react";

export default async function BillingPage() {
  const session = await getServerSession();
  const prisma = new PrismaClient();
  const user = await prisma.user.findUnique({ where: { email: session?.user?.email || "" } });

  const isPremium = user?.plan === "PREMIUM";

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="text-center mb-12">
        <h1 className="text-3xl font-bold mb-4">Pricing Plans</h1>
        <p className="text-slate-400">Upgrade your workspace to unlock the actual source code generated by the Hermes Agent.</p>
      </div>

      <div className="grid md:grid-cols-2 gap-8 max-w-3xl mx-auto">
        <div className="glass-panel p-8 rounded-2xl border border-slate-800">
          <h3 className="text-xl font-bold text-white mb-2">Basic Plan</h3>
          <p className="text-slate-400 text-sm mb-6">For generating and validating ideas.</p>
          <div className="text-3xl font-bold text-white mb-6">₹999 <span className="text-lg text-slate-500 font-normal">/ month</span></div>
          <ul className="space-y-3 mb-8">
            <li className="flex items-center gap-3 text-slate-300 text-sm"><CheckCircle2 className="text-primary w-5 h-5" /> Generate unlimited strategies</li>
            <li className="flex items-center gap-3 text-slate-300 text-sm"><CheckCircle2 className="text-primary w-5 h-5" /> Full backtest metrics</li>
            <li className="flex items-center gap-3 text-slate-300 text-sm"><CheckCircle2 className="text-primary w-5 h-5" /> View equity curves</li>
          </ul>
          <button disabled className="w-full py-3 rounded-xl bg-slate-800 text-slate-400 font-bold transition-colors">
            {isPremium ? "Downgrade" : "Current Plan"}
          </button>
        </div>

        <div className="glass-panel p-8 rounded-2xl border border-primary relative overflow-hidden">
          <div className="absolute top-0 right-0 bg-primary text-slate-950 text-xs font-bold px-3 py-1 rounded-bl-lg">RECOMMENDED</div>
          <div className="absolute inset-0 bg-primary/5 pointer-events-none" />
          
          <h3 className="text-xl font-bold text-white mb-2">Premium</h3>
          <p className="text-slate-400 text-sm mb-6">For serious automated traders.</p>
          <div className="text-3xl font-bold text-white mb-6">₹4,999 <span className="text-lg text-slate-500 font-normal">/ bot</span></div>
          <ul className="space-y-3 mb-8">
            <li className="flex items-center gap-3 text-slate-300 text-sm"><CheckCircle2 className="text-primary w-5 h-5" /> Everything in Basic</li>
            <li className="flex items-center gap-3 text-white font-medium text-sm"><Zap className="text-primary w-5 h-5" /> Download MQL5 / PineScript code</li>
            <li className="flex items-center gap-3 text-white font-medium text-sm"><CheckCircle2 className="text-primary w-5 h-5" /> Priority Hermes processing</li>
          </ul>
          <button className="w-full py-3 rounded-xl bg-primary text-slate-950 font-bold hover:bg-primary-hover transition-colors shadow-[0_0_15px_rgba(0,240,255,0.3)]">
            {isPremium ? "Active" : "Upgrade via Razorpay"}
          </button>
        </div>
      </div>
    </div>
  );
}
