import { NextResponse } from "next/server";
import { PrismaClient } from "@prisma/client";
import { getServerSession } from "next-auth";

export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  const session = await getServerSession();
  if (!session?.user?.email) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const prisma = new PrismaClient();
  const body = await request.json();
  const { prompt } = body;

  try {
    const user = await prisma.user.findUnique({ where: { email: session.user.email } });
    if (!user) throw new Error("User not found");

    // Mock Hermes Agent delay
    await new Promise(resolve => setTimeout(resolve, 8000));

    // Create the strategy and mock backtest results
    const strategy = await prisma.strategy.create({
      data: {
        userId: user.id,
        prompt,
        status: "COMPLETED",
        sourceCode: `// Auto-generated by Hermes Agent\n// Strategy: ${prompt}\n\n//@version=5\nstrategy("Hermes Bot", overlay=true)\n\n// Add your conditions here\nlongCondition = ta.crossover(ta.sma(close, 14), ta.sma(close, 28))\nif (longCondition)\n    strategy.entry("My Long Entry Id", strategy.long)\n\nshortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))\nif (shortCondition)\n    strategy.entry("My Short Entry Id", strategy.short)`,
        platform: "TradingView",
        results: {
          create: {
            winRate: 64.5,
            profitFactor: 1.8,
            maxDrawdown: 12.4,
            totalTrades: 342,
            equityCurve: JSON.stringify(Array.from({length: 30}, (_, i) => ({ day: i, value: 10000 + Math.random() * 5000 + (i * 200) })))
          }
        }
      }
    });

    return NextResponse.json(strategy);
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: "Failed to generate strategy" }, { status: 500 });
  }
}
